### ISSUE TITLE
Order is lost when pulling on lists

### ISSUE THREAD

**Issue by SevereOverfl0w** [lilactown/pyramid#36]
As discussed on [slack](https://clojurians.slack.com/archives/C02K5DCCA4X/p1722096497591969).

This appears to be down to the use of [into](https://github.com/lilactown/pyramid/blob/7b9b4c7416ecbeb1b85803c993630328db334099/src/pyramid/pull.cljc#L236) in the `list?` branch of the `visit` function.

**Comment by lilactown** [comment]
@SevereOverfl0w could you take a look at https://github.com/lilactown/pyramid/pull/37? Based on your slack message, I would expect the test in that branch to fail; it seems to pass in all runtimes.

Could you double check that you're using an up to date version of pyramid? If so, could you create a test that demonstrates the broken ordering?

**Comment by lilactown** [comment]
This was fixed in https://github.com/lilactown/pyramid/commit/77349e7e74e91165656933c45bfc0cabbe62b5fa by happenstance. I've done a release which includes this commit.
